In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np
import re
import requests
pd.set_option('max_colwidth', 80)

In [3]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36'}

In [4]:
job_link=[]
Category=[]

In [6]:
def extract_job_post(): 
    try:
        for i in range(0,10):
            url_next='https://www.rigzone.com/oil/jobs/search/?sk=machine+learning&page='+str(i)
            w1=requests.get(url_next,headers)
            soups=BeautifulSoup(w1.content,'html.parser') 
            soup=soups.findAll('a',href=True)
            for item in soup:
                if item['href'].startswith('/jobs/postings/'):
                    job_link.append('https://www.rigzone.com'+item['href'])
                    Category.append('machine_learning')
    except:
        pass
    return job_link,Category

In [7]:
job_link,Category=extract_job_post()

In [8]:
len(job_link)

200

In [9]:
len(Category)

200

In [10]:
Job_posting_df=pd.DataFrame({"Category":Category,"Job_Posting_link":job_link})
len(Job_posting_df)

200

In [11]:
Job_posting_df.head()

,Category,Job_Posting_link
0,machine_learning,https://www.rigzone.com/oil/jobs/postings/1133414_machine_learning_engineer?s=8
1,machine_learning,https://www.rigzone.com/oil/jobs/postings/1133110_machine_learning_engineer?s=8
2,machine_learning,https://www.rigzone.com/oil/jobs/postings/1133085_data_science_machine_learn...
3,machine_learning,https://www.rigzone.com/oil/jobs/postings/1132889_data_science_machine_learn...
4,machine_learning,https://www.rigzone.com/oil/jobs/postings/1135812_engineer_petrophysical_app...

In [10]:
#datascience
Job_posting_df['Job_Posting_link'][0]

'https://www.rigzone.com/oil/jobs/postings/1134504_data_science_engineer_i?s=8'

In [25]:
#machine learning
Job_posting_df['Job_Posting_link'][0]

'https://www.rigzone.com/oil/jobs/postings/1133414_machine_learning_engineer?s=8'

In [27]:
# Job_posting_df.to_csv('rigzone_jobpostings_links_datascience.csv',index=False)
# Job_posting_df.to_csv('rigzone_jobpostings_links_machinelearning.csv',index=False)

In [10]:
df=pd.read_csv('rigzone_jobpostings_links_datascience.csv')
df.head(1)
# df=pd.read_csv('rigzone_jobpostings_links_machinelearning.csv')
# df.head(1)

,Category,Job_Posting_link
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134504_data_science_engineer_i?s=8

In [11]:
df.shape

(1031, 2)

In [12]:
def rigzone_extract(df):
    rigzone_df=pd.DataFrame()
    for i in range(0,len(df)):
        print(i)
        try:
            Job_Posting_link=df['Job_Posting_link'][i]
            # Job_Posting_link='https://www.rigzone.com/oil/jobs/postings/1133414_machine_learning_engineer?s=8'
            # print(Job_Posting_link)
            Category=df['Category'][i]
            w2=requests.get(Job_Posting_link,headers)
            # print(w2.status_code)
            soups1=BeautifulSoup(w2.content,'html.parser') 
            Job_holder=soups1.find(class_='holder')
            Job_title=Job_holder.find('a').text
            # print(Job_title)
            content=soups1.find(class_='job-detail').findAll('span')
            Info=[]
            for c in content:
                Info.append(c.text)
            for ele in Info:
                if ele.strip().startswith('Education'):
                    Education=ele.replace('Education:','')
                if ele.strip().startswith('Skills'):
                    Skills=ele.replace('Skills:','')
                if ele.strip().startswith('Experience'):
                    Experience=ele.replace('Experience:','')
            try:
                if Education:
                    pass
            except:
                Education=None
            try:
                if Skills:
                    pass
            except:
                Skills=None
            try:
                if Experience:
                    pass
            except:
                Experience=None
            Details=[]
            for i in Job_holder.find('address'):
                # print(i.text)
                if i.text:
                    Details.append(i.text.replace('\n','').strip())
                    # Details.append(i.text)
            for ii in Details:
                if ii =='':
                    Details.remove(ii)
            Company_name=Details[0]
            # print(Company_name)
            try:
                Employer_type=Details[1]
            except:
                Employer_type=None
            # print(Employer_type)
            try:
                Location=Details[2]
            except:
                Location=None
            # print(Location)
            try:
                
                Descrip=soups1.find_all(class_='text')
                Description=Descrip[-1].text.replace('\n','').strip()
            except:
                Description=None
            # print(Description)
            rigzone1=pd.DataFrame({'Category':Category,'Job_Posting_link':Job_Posting_link,'Job_title':Job_title,'Company_name':Company_name,'Employer_type':Employer_type,'Location':Location,'Experience':Experience,'Education':Education,'Skills':Skills,'Description':[Description]},index=[0])
            # print(simplyhired1)
            rigzone_df=rigzone_df.append(rigzone1)
            # print(simplyhired_df)
        except Exception as e:
            print(e)
    return rigzone_df

In [283]:
# Job_Posting_link= 'https://www.rigzone.com/oil/jobs/postings/1133414_machine_learning_engineer?s=8'
# w2=requests.get(Job_Posting_link,headers)
# soups1=BeautifulSoup(w2.content,'html.parser')

In [282]:

# Description=[]
# Descrip=soups1.find_all(class_='text')
# # print(Descrip)
# for desc in Descrip:
#     # print(desc)
#     try:
#         print("lll")
#         Desc=desc.text
#         print(Desc)
#     except:
#         Desc=desc.find_all('b')
#         # print(Desc)
# for d in Desc:
#     Description.append(d)
# for d in Description:
#     if d=='':
#         Description.remove(d)

In [281]:
# Description=[]
# Descrip=soups1.find_all(class_='text')
# Desc=Descrip[-1].text
# Desc

In [13]:
df1=df[0:1]
df1
df.shape

(1031, 2)

In [14]:
rigzone=rigzone_extract(df)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
'NoneType' object has no attribute 'findAll'
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
'NoneType' object has no attribute 'findAll'
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
'NoneType' object has no attribute 'findAll'
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
'NoneType' object has no attribute 'findAll'
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
'NoneType' object has no attribute 'findAll'
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
'NoneType' object has no attribute 'findAll'
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
'NoneType' object has no attribute 'findAll'
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
'NoneType' object has no attribute 'findAll'
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
'NoneType' object has no attribute 'findAll'
499
'NoneType' object has no attribute 'findAll'
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
'NoneType' object has no attribute 'findAll'
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
'NoneType' object has no attribute 'findAll'
710
711
712
713
714
715
716
717
718
719
720
721
722
'NoneType' object has no attribute 'findAll'
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
'NoneType' object has no attribute 'findAll'
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
'NoneType' object has no attribute 'findAll'
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
'NoneType' object has no attribute 'findAll'
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
'NoneType' object has no attribute 'findAll'
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
'NoneType' object has no attribute 'findAll'
957
958
959
960
961
962
963
'NoneType' object has no attribute 'findAll'
964
965
966
967
968
969
970
971
972
973
974
'NoneType' object has no attribute 'findAll'
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030

In [15]:
rigzone.shape

(1011, 10)

In [16]:
rigzone

,Category,Job_Posting_link,Job_title,Company_name,Employer_type,Location,Experience,Education,Skills,Description
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134504_data_science_engineer_i?s=8,Data Science Engineer I,Nabors,Featured Employer,"Houston, Texas, United States",3 + Years,Bachelors/3-5 yr Degree,IT - Analysis & Management,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1133937_Data_Science_Engineer?s=8,Data Science Engineer,Strategic Resources European Recruitment Consultants Ltd,Featured Employer,"London, England, United Kingdom",3 + Years,High School/Secondary,"IT - Analysis & Management, IT - Networking & Telecom, IT - Programming & ...",Data Science EngineerPurpose of Role:The Data Science Engineer is responsibl...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134505_data_science_engineer_ii?s=8,Data Science Engineer II,Nabors,Featured Employer,"Houston, Texas, United States",3 + Years,Bachelors/3-5 yr Degree,IT - Analysis & Management,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134502_senior_data_science_engine...,Senior Data Science Engineer,Nabors,Featured Employer,"Houston, Texas, United States",6 + Years,Masters Degree,IT - Programming & Database,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134698_materials_modeling_data_sc...,Materials Modeling & Data Science Specialist,Saudi Aramco,Saudi Arabia,None,5 + Years,PhD/Doctorate,Modeling,Aramco energizes the world economy. \rAramco occupies a unique position in t...
...,...,...,...,...,...,...,...,...,...,...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1107310_senior_product_design_lead...,Product Design Lead (OFS-HQ) Remote,Baker Hughes,Featured Employer,"Houston, Texas, United States",7 + Years,Bachelors/3-5 yr Degree,"Graphics Design, IT - Software Development, Design Engineer",Product Design Lead (remote) Are you excited about digital and the opportu...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1084547_accountant?s=8,Accountant,Oceaneering,Featured Employer,"Aberdeen, United Kingdom",7 + Years,Bachelors/3-5 yr Degree,"Accounting, Financial Audit","Oceaneering pushes the frontiers of deep water, space and motion entertainme..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1103287_Tech_Prof-Completions_Sr?s=8,"Tech Prof-Completions, Sr",Halliburton,Featured Employer,"Perth, Western Australia, Australia",1 + Years,Bachelors/3-5 yr Degree,Workover or Completion,"About Halliburton Founded in 1919, Halliburton is one of the world’s leading..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1123603_field_service_reps?s=8,Field Service Reps,Core Lab,"USA, US",None,2 + Years,High School/Secondary,"Safety Officer, Safety Training Rep, Field Service Tech","FIELD SERVICE REPRESENTATIVE IMidland, TXKilgore, TX Sydney, MTGrand Junctio..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1062852_NAM_Industrial_Sales_Manag...,NAM Industrial Sales Manager -Nexus Controls--ALL US LOCATIONS,Baker Hughes,Featured Employer,"CO, US",2 + Years,Bachelors/3-5 yr Degree,Sales,Job Requirements Would you like to work with cutting-edge energy technology?...

In [17]:
rigzone.to_csv('rz_datascience.csv',index=False)
# rigzone.to_csv('rz_machinelearning.csv',index=False)

In [18]:
rigzone

,Category,Job_Posting_link,Job_title,Company_name,Employer_type,Location,Experience,Education,Skills,Description
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134504_data_science_engineer_i?s=8,Data Science Engineer I,Nabors,Featured Employer,"Houston, Texas, United States",3 + Years,Bachelors/3-5 yr Degree,IT - Analysis & Management,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1133937_Data_Science_Engineer?s=8,Data Science Engineer,Strategic Resources European Recruitment Consultants Ltd,Featured Employer,"London, England, United Kingdom",3 + Years,High School/Secondary,"IT - Analysis & Management, IT - Networking & Telecom, IT - Programming & ...",Data Science EngineerPurpose of Role:The Data Science Engineer is responsibl...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134505_data_science_engineer_ii?s=8,Data Science Engineer II,Nabors,Featured Employer,"Houston, Texas, United States",3 + Years,Bachelors/3-5 yr Degree,IT - Analysis & Management,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134502_senior_data_science_engine...,Senior Data Science Engineer,Nabors,Featured Employer,"Houston, Texas, United States",6 + Years,Masters Degree,IT - Programming & Database,Company OverviewNabors is a leading provider of advanced technology for the ...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1134698_materials_modeling_data_sc...,Materials Modeling & Data Science Specialist,Saudi Aramco,Saudi Arabia,None,5 + Years,PhD/Doctorate,Modeling,Aramco energizes the world economy. \rAramco occupies a unique position in t...
...,...,...,...,...,...,...,...,...,...,...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1107310_senior_product_design_lead...,Product Design Lead (OFS-HQ) Remote,Baker Hughes,Featured Employer,"Houston, Texas, United States",7 + Years,Bachelors/3-5 yr Degree,"Graphics Design, IT - Software Development, Design Engineer",Product Design Lead (remote) Are you excited about digital and the opportu...
0,data_science,https://www.rigzone.com/oil/jobs/postings/1084547_accountant?s=8,Accountant,Oceaneering,Featured Employer,"Aberdeen, United Kingdom",7 + Years,Bachelors/3-5 yr Degree,"Accounting, Financial Audit","Oceaneering pushes the frontiers of deep water, space and motion entertainme..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1103287_Tech_Prof-Completions_Sr?s=8,"Tech Prof-Completions, Sr",Halliburton,Featured Employer,"Perth, Western Australia, Australia",1 + Years,Bachelors/3-5 yr Degree,Workover or Completion,"About Halliburton Founded in 1919, Halliburton is one of the world’s leading..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1123603_field_service_reps?s=8,Field Service Reps,Core Lab,"USA, US",None,2 + Years,High School/Secondary,"Safety Officer, Safety Training Rep, Field Service Tech","FIELD SERVICE REPRESENTATIVE IMidland, TXKilgore, TX Sydney, MTGrand Junctio..."
0,data_science,https://www.rigzone.com/oil/jobs/postings/1062852_NAM_Industrial_Sales_Manag...,NAM Industrial Sales Manager -Nexus Controls--ALL US LOCATIONS,Baker Hughes,Featured Employer,"CO, US",2 + Years,Bachelors/3-5 yr Degree,Sales,Job Requirements Would you like to work with cutting-edge energy technology?...

In [ ]:
# Description=[]
# Descrip=soups1.find_all(class_='text')
# for desc in Descrip:
#     try:
#         Desc=desc.find_all('p')
#         # print(desc)
#     except:
#         Desc=desc.find_all('br')
#         # print(desc)
# print(Desc)
# for d in Desc:
#     print(d)
#     Description.append(d.contents)
# print(Description)
# for d in Description:
#     if d=='':
#         Description.remove(d)   
# # print(Description)